#!/bin/sh

# This configuration file is based on Catacomb's minimal config example.
# Compared to the minimal config, it starts various useful daemons if they
# are installed (such as gnome-calls and chatty).
#
# You are encouraged to modify it, to do so, copy it to ~/.config/catacomb/initrc.

# Key Bindings

## Launch `tzompantli` when holding the power button
catacomb msg bind-key --trigger press '*' XF86PowerOff sh -c \
    "sleep 0 0 0 0 0 0 0 0.5 &&
        if [ \"\$(catacomb msg dpms)\" = \"on\" ]; then
            (tremor 150 0 1; tzompantli)
        fi"

## Toggle display when pressing the power button
catacomb msg bind-key --trigger release '*' XF86PowerOff sh -c \
    "if pkill -SIGINT -xf \"sleep 0 0 0 0 0 0 0 0.5\"; then
        if [ \"\$(catacomb msg dpms)\" = \"on\" ]; then
            catacomb msg dpms off;
        else
            catacomb msg dpms on;
        fi
    fi"

## Take a screenshot on `power + volume down` and save it to /tmp/screenshot.png
catacomb msg bind-key --trigger press '*' XF86PowerOff+XF86AudioLowerVolume sh -c \
    "pkill -SIGINT -xf \"sleep 0 0 0 0 0 0 0 0.5\";
    tremor 150 0 1;
    geometry=\$(slurp 2>&1);
    if [ \$geometry = \"selection cancelled\" ]; then
        grim /tmp/screenshot.png;
    else
        grim -g \"\$geometry\" /tmp/screenshot.png;
    fi"

## Allow manually toggling the virtual keyboard
catacomb msg bind-key '*' EnableVirtualKeyboard \
    busctl call --user sm.puri.OSK0 /sm/puri/OSK0 sm.puri.OSK0 SetVisible b true
catacomb msg bind-key '*' AutoVirtualKeyboard \
    busctl call --user sm.puri.OSK0 /sm/puri/OSK0 sm.puri.OSK0 SetVisible b false

## Bind global volume keys
catacomb msg bind-key --trigger repeat '*' XF86AudioRaiseVolume \
    pactl set-sink-volume 0 +5%
catacomb msg bind-key --trigger repeat '*' XF86AudioLowerVolume \
    pactl set-sink-volume 0 -5%

# Turn off display after 3 minutes, suspend 30s later
systemctl="systemctl"
if ! command -v systemctl; then
    systemctl="loginctl"
fi
swayidle -w \
    timeout 180 "catacomb msg dpms off" \
    timeout 210 "$systemctl suspend" \
    before-sleep "catacomb msg dpms off" \
    after-resume \
        "# Resuspend after 30 seconds on wakeup with no activity.
        swayidle -w timeout 30 \"$systemctl suspend\" &
        sleep 30.1;
        kill \$!" &

# Ensure the virtual keyboard is enabled
gsettings set org.gnome.desktop.a11y.applications screen-keyboard-enabled true

# Set default background
tabula -i /usr/share/wallpapers/postmarketos.jpg &

# Spawn background apps
squeekboard &
epitaph &
gnome-calls --gapplication-service &
chatty --gapplication-service &

# Wait for completion
wait
